### PR TITLE
fix: handle pnpm monorepo `workspace:^` version correctly (#111)

### LINKED ISSUE #111: bug: replace pnpm `workspace:^` correctly
## Expected behavior

According to [pnpm docs](https://pnpm.io/workspaces#publishing-workspace-packages), `workspace: *` and other versions will be transformed from:

```json
{
    "dependencies": {
        "foo": "workspace:*",
        "bar": "workspace:~",
        "qar": "workspace:^",
        "zoo": "workspace:^1.5.0"
    }
}
```

to:

```json
{
    "dependencies": {
        "foo": "1.5.0",
        "bar": "~1.5.0",
        "qar": "^1.5.0",
        "zoo": "^1.5.0"
    }
}
```

## Current MSR behavior

```json
{
    "dependencies": {
        "foo": "1.5.0",
        "bar": "1.5.0",
        "qar": "1.5.0",
        "zoo": "(not tested)"
    }
}
```

### PR DESCRIPTION
**Pull request by lyh543**
resolve #111: support of replacing pnpm's `workspace:` dependencies version. [pnpm docs](https://pnpm.io/workspaces#publishing-workspace-packages)

**I modify current existing tests**, since I think it should work like this :P. Anyway, I may have misunderstanding on this project, so I'm happy to discuss with contributor.

After I'm allowed to modify current existing tests, I will add integration tests on monorepo that uses pnpm `workspace:` protocol.

---------

**Update: integration tests added.**

### CODE REVIEW

**Comment by lyh543** [comment]
## Why I modify the existing tests

Due to the `--deps.bump` docs from [README](https://github.com/dhoulb/multi-semantic-release/blob/master/README.md#cli):

> Define deps version update rule. 
> `override` — replace any prev version with the next one, 
> `satisfy` — check the next pkg version against its current references. If it matches (`*` matches to any, `1.1.0` matches `1.1.x`, `1.5.0` matches to `^1.0.0` and so on) release will not be triggered, if not `override` strategy will be applied instead;
> `inherit` will try to follow the current declaration version/range. `~1.0.0` + `minor` turns into `~1.1.0`, `1.x` + `major` gives `2.x`, but `1.x` + `minor` gives `1.x` so there will be no release, etc.

In [`yarnWorkspacesPackagesCarret`](https://github.com/dhoulb/multi-semantic-release/tree/master/test/fixtures/yarnWorkspacesPackagesCarret), all deps are defined like `^0.0.0`. In my opinion, with `inherit` as rule, deps version in new `package.json` should keep the `^1.0.0` style, so I update the test expectation.

Discussions are welcome👋

**Comment by antongolub** [comment]
We also experimented with the `workspace` protocol in https://github.com/semrel-extra/zx-bulk-release/blob/master/src/main/js/deps.js#L56.  I'm not sure if this implementation is correct, but it might be a starting point.

**Comment by lyh543** [comment]
> We also experimented with the `workspace` protocol in https://github.com/semrel-extra/zx-bulk-release/blob/master/src/main/js/deps.js#L56. I'm not sure if this implementation is correct, but it might be a starting point.

This implementation with regex is really simple! I'm so amazed that I refactored my code immediately.

BTW, can you review the part that modified existing tests? I wonder if I caught an bug or just misunderstood the code.

**Comment by antongolub** [comment]
@Badisi, @moroine, could you plz take a look?

File: lib/updateDeps.js [hunk 1]
```diff
@@ -306,7 +328,7 @@ const updateManifestDeps = (pkg, writeOut = true, bumpStrategy = "override", pre
 		scopes.forEach((scope) => {
 			if (scope[dependency.name]) {
 				scope[dependency.name] = resolveNextVersion(
-					get(dependency, "_lastRelease.version", "0.0.0"),
+					scope[dependency.name],
```
Comment (moroine) [inline lib/updateDeps.js:331]: I think this is the bugfix of `inherit` 🤔

**Review by moroine — COMMENTED** [review]
About the `inherit` change I think it's a breaking change but we didn't found out why we got this behavior. You can have a look at the discussion here.

https://github.com/dhoulb/multi-semantic-release/pull/101#issuecomment-1083157135

cc: @antongolub

File: lib/updateDeps.js (hunk 1 above)
Comment (antongolub) [reply lib/updateDeps.js:331]: Seems like that, so there's no need for yet another br change.

**Review by antongolub — APPROVED** [review]
